"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck.types import BaseModel
from apideck.utils import FieldMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ApplicantsFilterTypedDict(TypedDict):
    job_id: NotRequired[str]
    r"""Id of the job to filter on"""


class ApplicantsFilter(BaseModel):
    job_id: Annotated[Optional[str], FieldMetadata(query=True)] = None
    r"""Id of the job to filter on"""
