"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck.types import BaseModel
from typing_extensions import TypedDict


class UnifiedIDTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the resource"""


class UnifiedID(BaseModel):
    id: str
    r"""The unique identifier of the resource"""
