"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createcallbackstatedata import (
    CreateCallbackStateData,
    CreateCallbackStateDataTypedDict,
)
from .createcallbackstateresponse import (
    CreateCallbackStateResponse,
    CreateCallbackStateResponseTypedDict,
)
from .unexpectederrorresponse import (
    UnexpectedErrorResponse,
    UnexpectedErrorResponseTypedDict,
)
from apideck.types import BaseModel
from apideck.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class VaultCreateCallbackStateGlobalsTypedDict(TypedDict):
    customer_id: NotRequired[str]
    r"""ID of the consumer which you want to get or push data from"""
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class VaultCreateCallbackStateGlobals(BaseModel):
    customer_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-consumer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of the consumer which you want to get or push data from"""

    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


class VaultCreateCallbackStateRequestTypedDict(TypedDict):
    service_id: str
    r"""Service ID of the resource to return"""
    unified_api: str
    r"""Unified API"""
    create_callback_state_data: CreateCallbackStateDataTypedDict
    r"""Callback state data"""


class VaultCreateCallbackStateRequest(BaseModel):
    service_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Service ID of the resource to return"""

    unified_api: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unified API"""

    create_callback_state_data: Annotated[
        CreateCallbackStateData,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Callback state data"""


VaultCreateCallbackStateResponseTypedDict = TypeAliasType(
    "VaultCreateCallbackStateResponseTypedDict",
    Union[CreateCallbackStateResponseTypedDict, UnexpectedErrorResponseTypedDict],
)


VaultCreateCallbackStateResponse = TypeAliasType(
    "VaultCreateCallbackStateResponse",
    Union[CreateCallbackStateResponse, UnexpectedErrorResponse],
)
