"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from apideck.collections import Collections
from apideck.collectiontags import CollectionTags
from apideck.collectionticketcomments import CollectionTicketComments
from apideck.collectiontickets import CollectionTickets
from apideck.collectionusers import CollectionUsers


class IssueTracking(BaseSDK):
    collections: Collections
    collection_tickets: CollectionTickets
    collection_ticket_comments: CollectionTicketComments
    collection_users: CollectionUsers
    collection_tags: CollectionTags

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.collections = Collections(self.sdk_configuration)
        self.collection_tickets = CollectionTickets(self.sdk_configuration)
        self.collection_ticket_comments = CollectionTicketComments(
            self.sdk_configuration
        )
        self.collection_users = CollectionUsers(self.sdk_configuration)
        self.collection_tags = CollectionTags(self.sdk_configuration)
