"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from apideck.apideck_locations import ApideckLocations
from apideck.apideck_orders import ApideckOrders
from apideck.apideck_payments import ApideckPayments
from apideck.items import Items
from apideck.merchants import Merchants
from apideck.modifiergroups import ModifierGroups
from apideck.modifiers import Modifiers
from apideck.ordertypes import OrderTypes
from apideck.tenders import Tenders


class Pos(BaseSDK):
    orders: ApideckOrders
    payments: ApideckPayments
    merchants: Merchants
    locations: ApideckLocations
    items: Items
    modifiers: Modifiers
    modifier_groups: ModifierGroups
    order_types: OrderTypes
    tenders: Tenders

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.orders = ApideckOrders(self.sdk_configuration)
        self.payments = ApideckPayments(self.sdk_configuration)
        self.merchants = Merchants(self.sdk_configuration)
        self.locations = ApideckLocations(self.sdk_configuration)
        self.items = Items(self.sdk_configuration)
        self.modifiers = Modifiers(self.sdk_configuration)
        self.modifier_groups = ModifierGroups(self.sdk_configuration)
        self.order_types = OrderTypes(self.sdk_configuration)
        self.tenders = Tenders(self.sdk_configuration)
