"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "apideck-unify"
__version__: str = "0.31.10"
__openapi_doc_version__: str = "10.24.24"
__gen_version__: str = "2.753.1"
__user_agent__: str = "speakeasy-sdk/python 0.31.10 2.753.1 10.24.24 apideck-unify"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
