workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Apideck:
        inputs:
            - location: https://ci-spec-unify.s3.eu-central-1.amazonaws.com/speakeasy-spec.yml
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck
targets:
    apideck:
        target: python
        source: Apideck
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-python-code-samples
            blocking: false
