workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    apideck-OAS:
        inputs:
            - location: https://ci-spec-unify.s3.eu-central-1.amazonaws.com/speakeasy-spec.yml
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-oas
targets:
    apideck:
        target: python
        source: apideck-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-oas-code-samples
            blocking: false
