"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class AccountingConnectionCompanyTypedDict(TypedDict):
    r"""Represents a company/tenant/organization accessible through the current connection. Used for multi-company connectors where a single OAuth connection provides access to multiple companies."""

    id: NotRequired[str]
    r"""Unique identifier for the company in the downstream system. Use this value in the x-apideck-company-id header to scope requests to this company."""
    name: NotRequired[str]
    r"""Display name of the company"""


class AccountingConnectionCompany(BaseModel):
    r"""Represents a company/tenant/organization accessible through the current connection. Used for multi-company connectors where a single OAuth connection provides access to multiple companies."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: Optional[str] = None
    r"""Unique identifier for the company in the downstream system. Use this value in the x-apideck-company-id header to scope requests to this company."""

    name: Optional[str] = None
    r"""Display name of the company"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
