"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attachmentreferencetype import AttachmentReferenceType
from apideck_unify import models
from apideck_unify.types import BaseModel
from apideck_unify.utils import validate_open_enum
import pydantic
from pydantic import ConfigDict, field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AttachmentReferenceTypedDict(TypedDict):
    type: NotRequired[AttachmentReferenceType]
    id: NotRequired[str]
    r"""A unique identifier for an object."""


class AttachmentReference(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: Annotated[
        Optional[AttachmentReferenceType], PlainValidator(validate_open_enum(False))
    ] = None

    id: Optional[str] = None
    r"""A unique identifier for an object."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.AttachmentReferenceType(value)
            except ValueError:
                return value
        return value
