"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ledgeraccountcreateinput import (
    LedgerAccountCreateInput,
    LedgerAccountCreateInputTypedDict,
)
from apideck_unify.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BatchLedgerAccountsRequestItemsTypedDict(TypedDict):
    data: LedgerAccountCreateInputTypedDict
    r"""The writable shape of LedgerAccount for a batch create. Identical to [LedgerAccount](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body."""
    ref: NotRequired[str]
    r"""A caller-supplied reference for this item, echoed back on the matching result so each outcome can be tied to the record it came from. Must be unique within the request. Never sent to the connector."""


class BatchLedgerAccountsRequestItems(BaseModel):
    data: LedgerAccountCreateInput
    r"""The writable shape of LedgerAccount for a batch create. Identical to [LedgerAccount](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body."""

    ref: Annotated[Optional[str], pydantic.Field(alias="_ref")] = None
    r"""A caller-supplied reference for this item, echoed back on the matching result so each outcome can be tied to the record it came from. Must be unique within the request. Never sent to the connector."""


class BatchLedgerAccountsRequestTypedDict(TypedDict):
    r"""A batch of ledger accounts to write in a single request. Each item is processed independently: some may succeed while others fail, and the response carries one result per item in the order they were sent."""

    items: List[BatchLedgerAccountsRequestItemsTypedDict]
    r"""The records to write. The per-connector limit is the real cap and is usually lower than the ceiling here: read `batch_support.resources[<resource>].max_items` on the Connector API for the connector you are calling, or the resource gotchas. This ceiling exists so an oversized array is rejected by request validation before any per-item work runs, rather than after it."""


class BatchLedgerAccountsRequest(BaseModel):
    r"""A batch of ledger accounts to write in a single request. Each item is processed independently: some may succeed while others fail, and the response carries one result per item in the order they were sent."""

    items: List[BatchLedgerAccountsRequestItems]
    r"""The records to write. The per-connector limit is the real cap and is usually lower than the ceiling here: read `batch_support.resources[<resource>].max_items` on the Connector API for the connector you are calling, or the resource gotchas. This ceiling exists so an oversized array is rejected by request validation before any per-item work runs, rather than after it."""
