"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify import models, utils
from apideck_unify.types import BaseModel
from apideck_unify.utils import validate_open_enum
from enum import Enum
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BatchSupportMode(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another."""

    NONE = "none"
    NATIVE = "native"
    LOOP = "loop"


class BatchSupportResourcesMode(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""`none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests."""

    NONE = "none"
    NATIVE = "native"
    LOOP = "loop"


class ResourcesTypedDict(TypedDict):
    mode: BatchSupportResourcesMode
    r"""`none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests."""
    max_items: NotRequired[int]
    r"""The maximum number of items this resource accepts in one request. A request carrying more is rejected before any record is written. Resources on the same connector can differ: a resource that writes records one at a time is usually capped lower than one that writes them in a single call. Absent when the connector has not declared one, in which case the platform default applies."""


class Resources(BaseModel):
    mode: Annotated[
        BatchSupportResourcesMode, PlainValidator(validate_open_enum(False))
    ]
    r"""`none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests."""

    max_items: Optional[int] = None
    r"""The maximum number of items this resource accepts in one request. A request carrying more is rejected before any record is written. Resources on the same connector can differ: a resource that writes records one at a time is usually capped lower than one that writes them in a single call. Absent when the connector has not declared one, in which case the platform default applies."""

    @field_serializer("mode")
    def serialize_mode(self, value):
        if isinstance(value, str):
            try:
                return models.BatchSupportResourcesMode(value)
            except ValueError:
                return value
        return value


class BatchSupportTypedDict(TypedDict):
    r"""How this connector satisfies a batch write, per resource. Read this before calling a batch endpoint: support, execution mode and the per-request limit all vary by resource on the same connector, and the mode determines both latency and how many requests the call counts against your plan."""

    mode: BatchSupportMode
    r"""The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another."""
    resources: NotRequired[Dict[str, ResourcesTypedDict]]
    r"""Batch support for each resource that has a batch endpoint, keyed by the batch resource name (for example `invoices-batch`). A resource absent from this map, or reporting `none`, will refuse a batch request with a 501."""


class BatchSupport(BaseModel):
    r"""How this connector satisfies a batch write, per resource. Read this before calling a batch endpoint: support, execution mode and the per-request limit all vary by resource on the same connector, and the mode determines both latency and how many requests the call counts against your plan."""

    mode: Annotated[BatchSupportMode, PlainValidator(validate_open_enum(False))]
    r"""The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another."""

    resources: Optional[Dict[str, Resources]] = None
    r"""Batch support for each resource that has a batch endpoint, keyed by the batch resource name (for example `invoices-batch`). A resource absent from this map, or reporting `none`, will refuse a batch request with a 501."""

    @field_serializer("mode")
    def serialize_mode(self, value):
        if isinstance(value, str):
            try:
                return models.BatchSupportMode(value)
            except ValueError:
                return value
        return value
