"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bankaccount import BankAccount, BankAccountTypedDict
from .billlineitem_input import BillLineItemInput, BillLineItemInputTypedDict
from .currency import Currency
from .customfield import CustomField, CustomFieldTypedDict
from .linkedattachment import LinkedAttachment, LinkedAttachmentTypedDict
from .linkedledgeraccount import LinkedLedgerAccount, LinkedLedgerAccountTypedDict
from .linkedpaymentallocations import (
    LinkedPaymentAllocations,
    LinkedPaymentAllocationsTypedDict,
)
from .linkedsubsidiary_input import (
    LinkedSubsidiaryInput,
    LinkedSubsidiaryInputTypedDict,
)
from .linkedsupplier_input import LinkedSupplierInput, LinkedSupplierInputTypedDict
from .linkedtrackingcategory import (
    LinkedTrackingCategory,
    LinkedTrackingCategoryTypedDict,
)
from .passthroughbody import PassThroughBody, PassThroughBodyTypedDict
from apideck_unify import models, utils
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import validate_open_enum
from datetime import date
from enum import Enum
from pydantic import field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BillCreateInputStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Invoice status"""

    DRAFT = "draft"
    SUBMITTED = "submitted"
    AUTHORISED = "authorised"
    PARTIALLY_PAID = "partially_paid"
    PAID = "paid"
    VOID = "void"
    CREDIT = "credit"
    DELETED = "deleted"
    POSTED = "posted"


class BillCreateInputAmortizationType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Type of amortization"""

    MANUAL = "manual"
    RECEIPT = "receipt"
    SCHEDULE = "schedule"
    OTHER = "other"


class BillCreateInputTypedDict(TypedDict):
    r"""The writable shape of Bill for a batch create. Identical to [Bill](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body."""

    display_id: NotRequired[Nullable[str]]
    r"""Id to be displayed."""
    bill_number: NotRequired[Nullable[str]]
    r"""Reference to supplier bill number"""
    supplier: NotRequired[Nullable[LinkedSupplierInputTypedDict]]
    r"""The supplier this entity is linked to."""
    company_id: NotRequired[Nullable[str]]
    r"""The company ID the transaction belongs to"""
    subsidiary: NotRequired[Nullable[LinkedSubsidiaryInputTypedDict]]
    location_id: NotRequired[Nullable[str]]
    r"""The ID of the location"""
    department_id: NotRequired[Nullable[str]]
    r"""The ID of the department"""
    currency: NotRequired[Nullable[Currency]]
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""
    currency_rate: NotRequired[Nullable[float]]
    r"""Currency Exchange Rate at the time entity was recorded/generated."""
    tax_inclusive: NotRequired[Nullable[bool]]
    r"""Amounts are including tax"""
    bill_date: NotRequired[Nullable[date]]
    r"""Date bill was issued - YYYY-MM-DD."""
    due_date: NotRequired[Nullable[date]]
    r"""The due date is the date on which a payment is scheduled to be received - YYYY-MM-DD."""
    paid_date: NotRequired[Nullable[date]]
    r"""The paid date is the date on which a payment was sent to the supplier - YYYY-MM-DD."""
    po_number: NotRequired[Nullable[str]]
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""
    reference: NotRequired[Nullable[str]]
    r"""Optional reference identifier for the transaction."""
    line_items: NotRequired[List[BillLineItemInputTypedDict]]
    terms: NotRequired[Nullable[str]]
    r"""Terms of payment."""
    terms_id: NotRequired[Nullable[str]]
    r"""The ID of the payment terms"""
    balance: NotRequired[Nullable[float]]
    r"""Balance of bill due."""
    deposit: NotRequired[Nullable[float]]
    r"""Amount of deposit made to this bill."""
    sub_total: NotRequired[Nullable[float]]
    r"""Subtotal amount, normally before tax."""
    total_tax: NotRequired[Nullable[float]]
    r"""Total tax amount applied to this transaction."""
    total: NotRequired[Nullable[float]]
    r"""Total amount of bill, including tax."""
    tax_code: NotRequired[Nullable[str]]
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""
    notes: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[BillCreateInputStatus]]
    r"""Invoice status"""
    ledger_account: NotRequired[Nullable[LinkedLedgerAccountTypedDict]]
    payment_method: NotRequired[Nullable[str]]
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""
    channel: NotRequired[Nullable[str]]
    r"""The channel through which the transaction is processed."""
    language: NotRequired[Nullable[str]]
    r"""language code according to ISO 639-1. For the United States - EN"""
    accounting_by_row: NotRequired[Nullable[bool]]
    r"""Indicates if accounting by row is used (true) or not (false). Accounting by row means that a separate ledger transaction is created for each row."""
    bank_account: NotRequired[BankAccountTypedDict]
    discount_percentage: NotRequired[Nullable[float]]
    r"""Discount percentage applied to this transaction."""
    template_id: NotRequired[Nullable[str]]
    r"""Optional bill template"""
    approved_by: NotRequired[Nullable[str]]
    r"""The user who approved the bill"""
    amortization_type: NotRequired[Nullable[BillCreateInputAmortizationType]]
    r"""Type of amortization"""
    tax_method: NotRequired[Nullable[str]]
    r"""Method of tax calculation"""
    document_received: NotRequired[Nullable[bool]]
    r"""Whether the document has been received"""
    source_document_url: NotRequired[Nullable[str]]
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app. Currently only supported for Xero."""
    payment_allocations: NotRequired[
        Nullable[List[Nullable[LinkedPaymentAllocationsTypedDict]]]
    ]
    r"""A list of linked payment allocations."""
    tracking_categories: NotRequired[
        Nullable[List[Nullable[LinkedTrackingCategoryTypedDict]]]
    ]
    r"""A list of linked tracking categories."""
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    custom_fields: NotRequired[List[CustomFieldTypedDict]]
    pass_through: NotRequired[List[PassThroughBodyTypedDict]]
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""
    accounting_period: NotRequired[Nullable[str]]
    r"""Accounting period"""
    attachments: NotRequired[List[Nullable[LinkedAttachmentTypedDict]]]


class BillCreateInput(BaseModel):
    r"""The writable shape of Bill for a batch create. Identical to [Bill](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body."""

    display_id: OptionalNullable[str] = UNSET
    r"""Id to be displayed."""

    bill_number: OptionalNullable[str] = UNSET
    r"""Reference to supplier bill number"""

    supplier: OptionalNullable[LinkedSupplierInput] = UNSET
    r"""The supplier this entity is linked to."""

    company_id: OptionalNullable[str] = UNSET
    r"""The company ID the transaction belongs to"""

    subsidiary: OptionalNullable[LinkedSubsidiaryInput] = UNSET

    location_id: OptionalNullable[str] = UNSET
    r"""The ID of the location"""

    department_id: OptionalNullable[str] = UNSET
    r"""The ID of the department"""

    currency: Annotated[
        OptionalNullable[Currency], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""

    currency_rate: OptionalNullable[float] = UNSET
    r"""Currency Exchange Rate at the time entity was recorded/generated."""

    tax_inclusive: OptionalNullable[bool] = UNSET
    r"""Amounts are including tax"""

    bill_date: OptionalNullable[date] = UNSET
    r"""Date bill was issued - YYYY-MM-DD."""

    due_date: OptionalNullable[date] = UNSET
    r"""The due date is the date on which a payment is scheduled to be received - YYYY-MM-DD."""

    paid_date: OptionalNullable[date] = UNSET
    r"""The paid date is the date on which a payment was sent to the supplier - YYYY-MM-DD."""

    po_number: OptionalNullable[str] = UNSET
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""

    reference: OptionalNullable[str] = UNSET
    r"""Optional reference identifier for the transaction."""

    line_items: Optional[List[BillLineItemInput]] = None

    terms: OptionalNullable[str] = UNSET
    r"""Terms of payment."""

    terms_id: OptionalNullable[str] = UNSET
    r"""The ID of the payment terms"""

    balance: OptionalNullable[float] = UNSET
    r"""Balance of bill due."""

    deposit: OptionalNullable[float] = UNSET
    r"""Amount of deposit made to this bill."""

    sub_total: OptionalNullable[float] = UNSET
    r"""Subtotal amount, normally before tax."""

    total_tax: OptionalNullable[float] = UNSET
    r"""Total tax amount applied to this transaction."""

    total: OptionalNullable[float] = UNSET
    r"""Total amount of bill, including tax."""

    tax_code: OptionalNullable[str] = UNSET
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""

    notes: OptionalNullable[str] = UNSET

    status: Annotated[
        OptionalNullable[BillCreateInputStatus],
        PlainValidator(validate_open_enum(False)),
    ] = UNSET
    r"""Invoice status"""

    ledger_account: OptionalNullable[LinkedLedgerAccount] = UNSET

    payment_method: OptionalNullable[str] = UNSET
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""

    channel: OptionalNullable[str] = UNSET
    r"""The channel through which the transaction is processed."""

    language: OptionalNullable[str] = UNSET
    r"""language code according to ISO 639-1. For the United States - EN"""

    accounting_by_row: OptionalNullable[bool] = UNSET
    r"""Indicates if accounting by row is used (true) or not (false). Accounting by row means that a separate ledger transaction is created for each row."""

    bank_account: Optional[BankAccount] = None

    discount_percentage: OptionalNullable[float] = UNSET
    r"""Discount percentage applied to this transaction."""

    template_id: OptionalNullable[str] = UNSET
    r"""Optional bill template"""

    approved_by: OptionalNullable[str] = UNSET
    r"""The user who approved the bill"""

    amortization_type: Annotated[
        OptionalNullable[BillCreateInputAmortizationType],
        PlainValidator(validate_open_enum(False)),
    ] = UNSET
    r"""Type of amortization"""

    tax_method: OptionalNullable[str] = UNSET
    r"""Method of tax calculation"""

    document_received: OptionalNullable[bool] = UNSET
    r"""Whether the document has been received"""

    source_document_url: OptionalNullable[str] = UNSET
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app. Currently only supported for Xero."""

    payment_allocations: OptionalNullable[List[Nullable[LinkedPaymentAllocations]]] = (
        UNSET
    )
    r"""A list of linked payment allocations."""

    tracking_categories: OptionalNullable[List[Nullable[LinkedTrackingCategory]]] = (
        UNSET
    )
    r"""A list of linked tracking categories."""

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    custom_fields: Optional[List[CustomField]] = None

    pass_through: Optional[List[PassThroughBody]] = None
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""

    accounting_period: OptionalNullable[str] = UNSET
    r"""Accounting period"""

    attachments: Optional[List[Nullable[LinkedAttachment]]] = None

    @field_serializer("currency")
    def serialize_currency(self, value):
        if isinstance(value, str):
            try:
                return models.Currency(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.BillCreateInputStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("amortization_type")
    def serialize_amortization_type(self, value):
        if isinstance(value, str):
            try:
                return models.BillCreateInputAmortizationType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "display_id",
            "bill_number",
            "supplier",
            "company_id",
            "subsidiary",
            "location_id",
            "department_id",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "bill_date",
            "due_date",
            "paid_date",
            "po_number",
            "reference",
            "line_items",
            "terms",
            "terms_id",
            "balance",
            "deposit",
            "sub_total",
            "total_tax",
            "total",
            "tax_code",
            "notes",
            "status",
            "ledger_account",
            "payment_method",
            "channel",
            "language",
            "accounting_by_row",
            "bank_account",
            "discount_percentage",
            "template_id",
            "approved_by",
            "amortization_type",
            "tax_method",
            "document_received",
            "source_document_url",
            "payment_allocations",
            "tracking_categories",
            "row_version",
            "custom_fields",
            "pass_through",
            "accounting_period",
            "attachments",
        ]
        nullable_fields = [
            "display_id",
            "bill_number",
            "supplier",
            "company_id",
            "subsidiary",
            "location_id",
            "department_id",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "bill_date",
            "due_date",
            "paid_date",
            "po_number",
            "reference",
            "terms",
            "terms_id",
            "balance",
            "deposit",
            "sub_total",
            "total_tax",
            "total",
            "tax_code",
            "notes",
            "status",
            "ledger_account",
            "payment_method",
            "channel",
            "language",
            "accounting_by_row",
            "discount_percentage",
            "template_id",
            "approved_by",
            "amortization_type",
            "tax_method",
            "document_received",
            "source_document_url",
            "payment_allocations",
            "tracking_categories",
            "row_version",
            "accounting_period",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
