"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .benefit import Benefit, BenefitTypedDict
from .deduction import Deduction, DeductionTypedDict
from .tax import Tax, TaxTypedDict
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List
from typing_extensions import NotRequired, TypedDict


class CompensationTypedDict(TypedDict):
    employee_id: NotRequired[Nullable[str]]
    r"""A unique identifier for an object."""
    net_pay: NotRequired[Nullable[float]]
    r"""The employee's net pay. Only available when payroll has been processed"""
    gross_pay: NotRequired[Nullable[float]]
    r"""The employee's gross pay. Only available when payroll has been processed"""
    taxes: NotRequired[Nullable[List[TaxTypedDict]]]
    r"""An array of employer and employee taxes for the pay period."""
    deductions: NotRequired[Nullable[List[DeductionTypedDict]]]
    r"""An array of employee deductions for the pay period."""
    benefits: NotRequired[Nullable[List[BenefitTypedDict]]]
    r"""An array of employee benefits for the pay period."""


class Compensation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    employee_id: OptionalNullable[str] = UNSET
    r"""A unique identifier for an object."""

    net_pay: OptionalNullable[float] = UNSET
    r"""The employee's net pay. Only available when payroll has been processed"""

    gross_pay: OptionalNullable[float] = UNSET
    r"""The employee's gross pay. Only available when payroll has been processed"""

    taxes: OptionalNullable[List[Tax]] = UNSET
    r"""An array of employer and employee taxes for the pay period."""

    deductions: OptionalNullable[List[Deduction]] = UNSET
    r"""An array of employee deductions for the pay period."""

    benefits: OptionalNullable[List[Benefit]] = UNSET
    r"""An array of employee benefits for the pay period."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "employee_id",
            "net_pay",
            "gross_pay",
            "taxes",
            "deductions",
            "benefits",
        ]
        nullable_fields = [
            "employee_id",
            "net_pay",
            "gross_pay",
            "taxes",
            "deductions",
            "benefits",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
