"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify.types import BaseModel
from typing_extensions import TypedDict


class ConnectionMigrateDataTypedDict(TypedDict):
    target_service_id: str
    r"""The service id of the connector to migrate this connection to. Must be one of the source connector's declared migration targets."""


class ConnectionMigrateData(BaseModel):
    target_service_id: str
    r"""The service id of the connector to migrate this connection to. Must be one of the source connector's declared migration targets."""
