"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datascopesresources import DataScopesResources, DataScopesResourcesTypedDict
from apideck_unify.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ConsentRecordTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Unique identifier for this consent record"""
    created_at: NotRequired[str]
    r"""ISO timestamp when consent was recorded"""
    granted: NotRequired[bool]
    r"""Whether consent was granted (true) or denied/revoked (false)"""
    resources: NotRequired[DataScopesResourcesTypedDict]
    r"""Data scopes resource configuration that can be either detailed field permissions or a wildcard"""


class ConsentRecord(BaseModel):
    id: Optional[str] = None
    r"""Unique identifier for this consent record"""

    created_at: Optional[str] = None
    r"""ISO timestamp when consent was recorded"""

    granted: Optional[bool] = None
    r"""Whether consent was granted (true) or denied/revoked (false)"""

    resources: Optional[DataScopesResources] = None
    r"""Data scopes resource configuration that can be either detailed field permissions or a wildcard"""
