"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify import models, utils
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import ConfigDict, field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict
from typing_extensions import Annotated, NotRequired, TypedDict


class EmailType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Email type"""

    PRIMARY = "primary"
    SECONDARY = "secondary"
    WORK = "work"
    PERSONAL = "personal"
    BILLING = "billing"
    OTHER = "other"


class EmailTypedDict(TypedDict):
    id: NotRequired[Nullable[str]]
    r"""Unique identifier for the email address"""
    email: NotRequired[Nullable[str]]
    r"""Email address"""
    type: NotRequired[Nullable[EmailType]]
    r"""Email type"""


class Email(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: OptionalNullable[str] = UNSET
    r"""Unique identifier for the email address"""

    email: OptionalNullable[str] = UNSET
    r"""Email address"""

    type: Annotated[
        OptionalNullable[EmailType], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Email type"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.EmailType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "email", "type"]
        nullable_fields = ["id", "email", "type"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
