"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .linkedledgeraccount import LinkedLedgerAccount, LinkedLedgerAccountTypedDict
from .linkedtaxrate import LinkedTaxRate, LinkedTaxRateTypedDict
from .linkedtaxrate_input import LinkedTaxRateInput, LinkedTaxRateInputTypedDict
from .passthroughbody import PassThroughBody, PassThroughBodyTypedDict
from apideck_unify import models, utils
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import validate_open_enum
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import ConfigDict, field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExpenseCategoryStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the expense category."""

    ACTIVE = "active"
    INACTIVE = "inactive"


class ExpenseCategoryTypedDict(TypedDict):
    id: NotRequired[str]
    r"""A unique identifier for an object."""
    display_id: NotRequired[Nullable[str]]
    r"""Id to be displayed."""
    name: NotRequired[str]
    r"""The name of the expense category."""
    code: NotRequired[Nullable[str]]
    r"""The code or external identifier of the expense category."""
    description: NotRequired[Nullable[str]]
    r"""The description of the expense category."""
    status: NotRequired[Nullable[ExpenseCategoryStatus]]
    r"""The status of the expense category."""
    account: NotRequired[Nullable[LinkedLedgerAccountTypedDict]]
    offset_account: NotRequired[Nullable[LinkedLedgerAccountTypedDict]]
    tax_rate: NotRequired[LinkedTaxRateTypedDict]
    rate_required: NotRequired[Nullable[bool]]
    r"""Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile)."""
    default_rate: NotRequired[Nullable[float]]
    r"""Default rate when rate_required is true (e.g. 0.67 for mileage)."""
    custom_mappings: NotRequired[Nullable[Dict[str, Any]]]
    r"""When custom mappings are configured on the resource, the result is included here."""
    downstream_id: NotRequired[Nullable[str]]
    r"""The third-party API ID of original entity"""
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    updated_by: NotRequired[Nullable[str]]
    r"""The user who last updated the object."""
    created_by: NotRequired[Nullable[str]]
    r"""The user who created the object."""
    updated_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was last updated."""
    created_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was created."""
    pass_through: NotRequired[List[PassThroughBodyTypedDict]]
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""


class ExpenseCategory(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: Optional[str] = None
    r"""A unique identifier for an object."""

    display_id: OptionalNullable[str] = UNSET
    r"""Id to be displayed."""

    name: Optional[str] = None
    r"""The name of the expense category."""

    code: OptionalNullable[str] = UNSET
    r"""The code or external identifier of the expense category."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the expense category."""

    status: Annotated[
        OptionalNullable[ExpenseCategoryStatus],
        PlainValidator(validate_open_enum(False)),
    ] = UNSET
    r"""The status of the expense category."""

    account: OptionalNullable[LinkedLedgerAccount] = UNSET

    offset_account: OptionalNullable[LinkedLedgerAccount] = UNSET

    tax_rate: Optional[LinkedTaxRate] = None

    rate_required: OptionalNullable[bool] = UNSET
    r"""Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile)."""

    default_rate: OptionalNullable[float] = UNSET
    r"""Default rate when rate_required is true (e.g. 0.67 for mileage)."""

    custom_mappings: OptionalNullable[Dict[str, Any]] = UNSET
    r"""When custom mappings are configured on the resource, the result is included here."""

    downstream_id: OptionalNullable[str] = UNSET
    r"""The third-party API ID of original entity"""

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    updated_by: OptionalNullable[str] = UNSET
    r"""The user who last updated the object."""

    created_by: OptionalNullable[str] = UNSET
    r"""The user who created the object."""

    updated_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was last updated."""

    created_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was created."""

    pass_through: Optional[List[PassThroughBody]] = None
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.ExpenseCategoryStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "id",
            "display_id",
            "name",
            "code",
            "description",
            "status",
            "account",
            "offset_account",
            "tax_rate",
            "rate_required",
            "default_rate",
            "custom_mappings",
            "downstream_id",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
            "pass_through",
        ]
        nullable_fields = [
            "display_id",
            "code",
            "description",
            "status",
            "account",
            "offset_account",
            "rate_required",
            "default_rate",
            "custom_mappings",
            "downstream_id",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m


class ExpenseCategoryInputTypedDict(TypedDict):
    display_id: NotRequired[Nullable[str]]
    r"""Id to be displayed."""
    name: NotRequired[str]
    r"""The name of the expense category."""
    code: NotRequired[Nullable[str]]
    r"""The code or external identifier of the expense category."""
    description: NotRequired[Nullable[str]]
    r"""The description of the expense category."""
    status: NotRequired[Nullable[ExpenseCategoryStatus]]
    r"""The status of the expense category."""
    account: NotRequired[Nullable[LinkedLedgerAccountTypedDict]]
    offset_account: NotRequired[Nullable[LinkedLedgerAccountTypedDict]]
    tax_rate: NotRequired[LinkedTaxRateInputTypedDict]
    rate_required: NotRequired[Nullable[bool]]
    r"""Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile)."""
    default_rate: NotRequired[Nullable[float]]
    r"""Default rate when rate_required is true (e.g. 0.67 for mileage)."""
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    pass_through: NotRequired[List[PassThroughBodyTypedDict]]
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""


class ExpenseCategoryInput(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    display_id: OptionalNullable[str] = UNSET
    r"""Id to be displayed."""

    name: Optional[str] = None
    r"""The name of the expense category."""

    code: OptionalNullable[str] = UNSET
    r"""The code or external identifier of the expense category."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the expense category."""

    status: Annotated[
        OptionalNullable[ExpenseCategoryStatus],
        PlainValidator(validate_open_enum(False)),
    ] = UNSET
    r"""The status of the expense category."""

    account: OptionalNullable[LinkedLedgerAccount] = UNSET

    offset_account: OptionalNullable[LinkedLedgerAccount] = UNSET

    tax_rate: Optional[LinkedTaxRateInput] = None

    rate_required: OptionalNullable[bool] = UNSET
    r"""Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile)."""

    default_rate: OptionalNullable[float] = UNSET
    r"""Default rate when rate_required is true (e.g. 0.67 for mileage)."""

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    pass_through: Optional[List[PassThroughBody]] = None
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.ExpenseCategoryStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "display_id",
            "name",
            "code",
            "description",
            "status",
            "account",
            "offset_account",
            "tax_rate",
            "rate_required",
            "default_rate",
            "row_version",
            "pass_through",
        ]
        nullable_fields = [
            "display_id",
            "code",
            "description",
            "status",
            "account",
            "offset_account",
            "rate_required",
            "default_rate",
            "row_version",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
