"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .simpleformfieldoption import SimpleFormFieldOption, SimpleFormFieldOptionTypedDict
from apideck_unify import models, utils
from apideck_unify.types import BaseModel
from apideck_unify.utils import validate_open_enum
from enum import Enum
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FormFieldOptionGroupOptionType(str, Enum, metaclass=utils.OpenEnumMeta):
    GROUP = "group"


class FormFieldOptionGroupTypedDict(TypedDict):
    id: NotRequired[str]
    label: NotRequired[str]
    options: NotRequired[List[SimpleFormFieldOptionTypedDict]]
    option_type: NotRequired[FormFieldOptionGroupOptionType]


class FormFieldOptionGroup(BaseModel):
    id: Optional[str] = None

    label: Optional[str] = None

    options: Optional[List[SimpleFormFieldOption]] = None

    option_type: Annotated[
        Optional[FormFieldOptionGroupOptionType],
        PlainValidator(validate_open_enum(False)),
    ] = None

    @field_serializer("option_type")
    def serialize_option_type(self, value):
        if isinstance(value, str):
            try:
                return models.FormFieldOptionGroupOptionType(value)
            except ValueError:
                return value
        return value
