"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customfield import CustomField, CustomFieldTypedDict
from .linkedinvoiceitem import LinkedInvoiceItem, LinkedInvoiceItemTypedDict
from .linkedpurchaseorder import LinkedPurchaseOrder, LinkedPurchaseOrderTypedDict
from .linkedtrackingcategory import (
    LinkedTrackingCategory,
    LinkedTrackingCategoryTypedDict,
)
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GoodsReceiptLineItemTypedDict(TypedDict):
    id: NotRequired[str]
    r"""A unique identifier for an object."""
    line_number: NotRequired[Nullable[int]]
    r"""Line number of the resource"""
    purchase_order: NotRequired[Nullable[LinkedPurchaseOrderTypedDict]]
    item: NotRequired[LinkedInvoiceItemTypedDict]
    description: NotRequired[Nullable[str]]
    r"""Description of the received item as recorded on the receipt line."""
    quantity_received: NotRequired[Nullable[float]]
    r"""Quantity received on this line, in the line's unit of measure."""
    quantity_ordered: NotRequired[Nullable[float]]
    r"""Quantity ordered on the linked purchase order line, when the accounting system exposes it on the receipt line."""
    unit_of_measure: NotRequired[Nullable[str]]
    r"""Description of the unit type the item is sold as, ie: kg, hour."""
    unit_price: NotRequired[Nullable[float]]
    total_amount: NotRequired[Nullable[float]]
    r"""Value of the received quantity on this line, when the accounting system records a cost on the receipt."""
    location_id: NotRequired[Nullable[str]]
    r"""ID of the warehouse, storage location or bin the line was received into."""
    tracking_categories: NotRequired[
        Nullable[List[Nullable[LinkedTrackingCategoryTypedDict]]]
    ]
    r"""A list of linked tracking categories."""
    custom_fields: NotRequired[List[CustomFieldTypedDict]]
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    updated_by: NotRequired[Nullable[str]]
    r"""The user who last updated the object."""
    created_by: NotRequired[Nullable[str]]
    r"""The user who created the object."""
    updated_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was last updated."""
    created_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was created."""


class GoodsReceiptLineItem(BaseModel):
    id: Optional[str] = None
    r"""A unique identifier for an object."""

    line_number: OptionalNullable[int] = UNSET
    r"""Line number of the resource"""

    purchase_order: OptionalNullable[LinkedPurchaseOrder] = UNSET

    item: Optional[LinkedInvoiceItem] = None

    description: OptionalNullable[str] = UNSET
    r"""Description of the received item as recorded on the receipt line."""

    quantity_received: OptionalNullable[float] = UNSET
    r"""Quantity received on this line, in the line's unit of measure."""

    quantity_ordered: OptionalNullable[float] = UNSET
    r"""Quantity ordered on the linked purchase order line, when the accounting system exposes it on the receipt line."""

    unit_of_measure: OptionalNullable[str] = UNSET
    r"""Description of the unit type the item is sold as, ie: kg, hour."""

    unit_price: OptionalNullable[float] = UNSET

    total_amount: OptionalNullable[float] = UNSET
    r"""Value of the received quantity on this line, when the accounting system records a cost on the receipt."""

    location_id: OptionalNullable[str] = UNSET
    r"""ID of the warehouse, storage location or bin the line was received into."""

    tracking_categories: OptionalNullable[List[Nullable[LinkedTrackingCategory]]] = (
        UNSET
    )
    r"""A list of linked tracking categories."""

    custom_fields: Optional[List[CustomField]] = None

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    updated_by: OptionalNullable[str] = UNSET
    r"""The user who last updated the object."""

    created_by: OptionalNullable[str] = UNSET
    r"""The user who created the object."""

    updated_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was last updated."""

    created_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was created."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "id",
            "line_number",
            "purchase_order",
            "item",
            "description",
            "quantity_received",
            "quantity_ordered",
            "unit_of_measure",
            "unit_price",
            "total_amount",
            "location_id",
            "tracking_categories",
            "custom_fields",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
        ]
        nullable_fields = [
            "line_number",
            "purchase_order",
            "description",
            "quantity_received",
            "quantity_ordered",
            "unit_of_measure",
            "unit_price",
            "total_amount",
            "location_id",
            "tracking_categories",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
