"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ecommerceorderstatus import EcommerceOrderStatus
from apideck_unify import models
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import validate_open_enum
import pydantic
from pydantic import ConfigDict, field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LinkedEcommerceOrderTypedDict(TypedDict):
    r"""The order this entity is linked to."""

    id: NotRequired[str]
    r"""A unique identifier for an object."""
    total: NotRequired[Nullable[str]]
    r"""The total amount of the order."""
    status: NotRequired[Nullable[EcommerceOrderStatus]]
    r"""Current status of the order."""


class LinkedEcommerceOrder(BaseModel):
    r"""The order this entity is linked to."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: Optional[str] = None
    r"""A unique identifier for an object."""

    total: OptionalNullable[str] = UNSET
    r"""The total amount of the order."""

    status: Annotated[
        OptionalNullable[EcommerceOrderStatus],
        PlainValidator(validate_open_enum(False)),
    ] = UNSET
    r"""Current status of the order."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.EcommerceOrderStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "total", "status"]
        nullable_fields = ["total", "status"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
