"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from apideck_unify.types import BaseModel
from apideck_unify.utils import FieldMetadata, HeaderMetadata
import httpx
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProxyGetProxyGlobalsTypedDict(TypedDict):
    consumer_id: NotRequired[str]
    r"""ID of the consumer which you want to get or push data from"""
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class ProxyGetProxyGlobals(BaseModel):
    consumer_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-consumer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of the consumer which you want to get or push data from"""

    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


class ProxyGetProxyRequestTypedDict(TypedDict):
    service_id: str
    r"""Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API."""
    downstream_url: str
    r"""Downstream URL"""
    consumer_id: NotRequired[str]
    r"""ID of the consumer which you want to get or push data from"""
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""
    unified_api: NotRequired[str]
    r"""Specify which unified API to use for the connection lookup. Required for multi-API connectors (e.g., Workday) to ensure the correct credentials are used."""
    downstream_authorization: NotRequired[str]
    r"""Downstream authorization header. This will skip the Vault token injection."""
    timeout: NotRequired[int]
    r"""Override the default downstream request timeout in milliseconds. The default is 28000 (28 seconds)."""
    follow_redirects: NotRequired[bool]
    r"""Set to `false` to opt out of the redirect to the presigned download URL. Instead of a `30x` response, you receive a `200` JSON body `{ url, expires_at }` containing the URL and its expiry, which you can fetch explicitly. Use this if your client automatically forwards the `Authorization` header onto redirects, since the downstream storage provider will reject that request. Any value other than `false` (or omitting the header) preserves the default redirect behavior."""


class ProxyGetProxyRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="x-apideck-service-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API."""

    downstream_url: Annotated[
        str,
        pydantic.Field(alias="x-apideck-downstream-url"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Downstream URL"""

    consumer_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-consumer-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of the consumer which you want to get or push data from"""

    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""

    unified_api: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-unified-api"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Specify which unified API to use for the connection lookup. Required for multi-API connectors (e.g., Workday) to ensure the correct credentials are used."""

    downstream_authorization: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-downstream-authorization"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""Downstream authorization header. This will skip the Vault token injection."""

    timeout: Annotated[
        Optional[int],
        pydantic.Field(alias="x-apideck-timeout"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = 28000
    r"""Override the default downstream request timeout in milliseconds. The default is 28000 (28 seconds)."""

    follow_redirects: Annotated[
        Optional[bool],
        pydantic.Field(alias="x-apideck-follow-redirects"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = True
    r"""Set to `false` to opt out of the redirect to the presigned download URL. Instead of a `30x` response, you receive a `200` JSON body `{ url, expires_at }` containing the URL and its expiry, which you can fetch explicitly. Use this if your client automatically forwards the `Authorization` header onto redirects, since the downstream storage provider will reject that request. Any value other than `false` (or omitting the header) preserves the default redirect behavior."""


class ProxyGetProxyResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    headers: Dict[str, List[str]]
    response_json: NotRequired[Dict[str, Any]]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    response_binary: NotRequired[httpx.Response]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    response_pdf: NotRequired[httpx.Response]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    response_xml: NotRequired[str]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    response_csv: NotRequired[str]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    response_text: NotRequired[str]
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""
    error_json: NotRequired[Dict[str, Any]]
    r"""Proxy error"""
    error_xml: NotRequired[str]
    r"""Proxy error"""
    error_html: NotRequired[str]
    r"""Proxy error"""
    error_text: NotRequired[str]
    r"""Proxy error"""


class ProxyGetProxyResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    headers: Dict[str, List[str]]

    response_json: Optional[Dict[str, Any]] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    response_binary: Optional[httpx.Response] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    response_pdf: Optional[httpx.Response] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    response_xml: Optional[str] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    response_csv: Optional[str] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    response_text: Optional[str] = None
    r"""Ok. When the request includes `x-apideck-follow-redirects: false` and the downstream response would otherwise redirect to a presigned URL (oversized responses), the body is instead an `application/json` object `{ url, expires_at }` — fetch `url` explicitly (without the Authorization header) to retrieve the payload."""

    error_json: Optional[Dict[str, Any]] = None
    r"""Proxy error"""

    error_xml: Optional[str] = None
    r"""Proxy error"""

    error_html: Optional[str] = None
    r"""Proxy error"""

    error_text: Optional[str] = None
    r"""Proxy error"""
