"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from .currency import Currency
from .customfield import CustomField, CustomFieldTypedDict
from .invoicelineitem import (
    InvoiceLineItem,
    InvoiceLineItemInput,
    InvoiceLineItemInputTypedDict,
    InvoiceLineItemTypedDict,
)
from .linkedcustomer import LinkedCustomer, LinkedCustomerTypedDict
from .linkedcustomer_input import LinkedCustomerInput, LinkedCustomerInputTypedDict
from .linkedtrackingcategory import (
    LinkedTrackingCategory,
    LinkedTrackingCategoryTypedDict,
)
from .passthroughbody import PassThroughBody, PassThroughBodyTypedDict
from apideck_unify import models, utils
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import validate_open_enum
from datetime import date, datetime
from enum import Enum
from pydantic import field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SalesOrderStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Sales order status, in order of precedence: `cancelled`; `closed` (the order is closed or completed, whether or not it was billed); `invoiced` (fully billed but not yet closed); `back_ordered`; `on_hold` (including credit hold); `draft` (including pending approval); `open` (every other active state, including partially shipped and partially invoiced); `other` for states that fit none of these."""

    DRAFT = "draft"
    OPEN = "open"
    ON_HOLD = "on_hold"
    BACK_ORDERED = "back_ordered"
    INVOICED = "invoiced"
    CLOSED = "closed"
    CANCELLED = "cancelled"
    OTHER = "other"


class SalesOrderTypedDict(TypedDict):
    id: NotRequired[str]
    r"""A unique identifier for an object."""
    downstream_id: NotRequired[Nullable[str]]
    r"""The third-party API ID of original entity"""
    number: NotRequired[Nullable[str]]
    r"""Sales order number, as assigned by the accounting system."""
    customer: NotRequired[Nullable[LinkedCustomerTypedDict]]
    r"""The customer this entity is linked to."""
    quote_id: NotRequired[Nullable[str]]
    r"""The unique identifier for the quote."""
    invoice_id: NotRequired[Nullable[str]]
    r"""ID of the invoice created from this sales order. Populated when the accounting system records a single invoice on the order (see the connector gotchas); null when the order has not been invoiced, or when it was invoiced in parts and the system keeps no single link."""
    company_id: NotRequired[Nullable[str]]
    r"""The company ID the transaction belongs to"""
    department_id: NotRequired[Nullable[str]]
    r"""The ID of the department"""
    location_id: NotRequired[Nullable[str]]
    r"""The ID of the location"""
    project_id: NotRequired[str]
    r"""The unique identifier for the linked project."""
    subsidiary_id: NotRequired[Nullable[str]]
    r"""The ID of the subsidiary"""
    order_date: NotRequired[Nullable[date]]
    r"""Date the sales order was placed - YYYY-MM-DD."""
    delivery_date: NotRequired[Nullable[date]]
    r"""The requested delivery date: the date the customer asked to receive the goods or services - YYYY-MM-DD. Promised ship dates and payment due dates are not mapped here."""
    order_type: NotRequired[Nullable[str]]
    r"""The order or transaction type of the sales order, as configured in the accounting system. On create, selects the type to create when the system supports several; omit to use the connection default. See the connector gotchas for the values each system accepts."""
    terms: NotRequired[Nullable[str]]
    r"""Payment terms of the sales order."""
    terms_id: NotRequired[Nullable[str]]
    r"""The ID of the payment terms"""
    po_number: NotRequired[Nullable[str]]
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""
    reference: NotRequired[Nullable[str]]
    r"""Optional reference identifier for the transaction."""
    status: NotRequired[Nullable[SalesOrderStatus]]
    r"""Sales order status, in order of precedence: `cancelled`; `closed` (the order is closed or completed, whether or not it was billed); `invoiced` (fully billed but not yet closed); `back_ordered`; `on_hold` (including credit hold); `draft` (including pending approval); `open` (every other active state, including partially shipped and partially invoiced); `other` for states that fit none of these."""
    currency: NotRequired[Nullable[Currency]]
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""
    currency_rate: NotRequired[Nullable[float]]
    r"""Currency Exchange Rate at the time entity was recorded/generated."""
    tax_inclusive: NotRequired[Nullable[bool]]
    r"""Amounts are including tax"""
    sub_total: NotRequired[Nullable[float]]
    r"""Sub-total amount, normally before tax."""
    total_tax: NotRequired[Nullable[float]]
    r"""Total tax amount applied to this sales order."""
    tax_code: NotRequired[Nullable[str]]
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""
    discount_percentage: NotRequired[Nullable[float]]
    r"""Discount percentage applied to this sales order."""
    discount_amount: NotRequired[Nullable[float]]
    r"""Discount amount applied to this sales order."""
    total: NotRequired[Nullable[float]]
    r"""Total amount of the sales order, including tax."""
    unbilled_amount: NotRequired[Nullable[float]]
    r"""Amount of the sales order not yet invoiced. Not the amount owed: see `balance` on the invoices created from the order for that."""
    shipping_method: NotRequired[Nullable[str]]
    r"""Shipping method or carrier code for the order."""
    payment_method: NotRequired[Nullable[str]]
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""
    customer_memo: NotRequired[Nullable[str]]
    r"""Message to the customer, shown on the sales order."""
    notes: NotRequired[Nullable[str]]
    r"""Internal notes for the sales order, not shown to the customer."""
    line_items: NotRequired[List[InvoiceLineItemTypedDict]]
    billing_address: NotRequired[AddressTypedDict]
    shipping_address: NotRequired[AddressTypedDict]
    tracking_categories: NotRequired[
        Nullable[List[Nullable[LinkedTrackingCategoryTypedDict]]]
    ]
    r"""A list of linked tracking categories."""
    template_id: NotRequired[Nullable[str]]
    r"""Optional sales order template"""
    source_document_url: NotRequired[Nullable[str]]
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app."""
    custom_mappings: NotRequired[Nullable[Dict[str, Any]]]
    r"""When custom mappings are configured on the resource, the result is included here."""
    custom_fields: NotRequired[List[CustomFieldTypedDict]]
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    updated_by: NotRequired[Nullable[str]]
    r"""The user who last updated the object."""
    created_by: NotRequired[Nullable[str]]
    r"""The user who created the object."""
    updated_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was last updated."""
    created_at: NotRequired[Nullable[datetime]]
    r"""The date and time when the object was created."""
    pass_through: NotRequired[List[PassThroughBodyTypedDict]]
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""


class SalesOrder(BaseModel):
    id: Optional[str] = None
    r"""A unique identifier for an object."""

    downstream_id: OptionalNullable[str] = UNSET
    r"""The third-party API ID of original entity"""

    number: OptionalNullable[str] = UNSET
    r"""Sales order number, as assigned by the accounting system."""

    customer: OptionalNullable[LinkedCustomer] = UNSET
    r"""The customer this entity is linked to."""

    quote_id: OptionalNullable[str] = UNSET
    r"""The unique identifier for the quote."""

    invoice_id: OptionalNullable[str] = UNSET
    r"""ID of the invoice created from this sales order. Populated when the accounting system records a single invoice on the order (see the connector gotchas); null when the order has not been invoiced, or when it was invoiced in parts and the system keeps no single link."""

    company_id: OptionalNullable[str] = UNSET
    r"""The company ID the transaction belongs to"""

    department_id: OptionalNullable[str] = UNSET
    r"""The ID of the department"""

    location_id: OptionalNullable[str] = UNSET
    r"""The ID of the location"""

    project_id: Optional[str] = None
    r"""The unique identifier for the linked project."""

    subsidiary_id: OptionalNullable[str] = UNSET
    r"""The ID of the subsidiary"""

    order_date: OptionalNullable[date] = UNSET
    r"""Date the sales order was placed - YYYY-MM-DD."""

    delivery_date: OptionalNullable[date] = UNSET
    r"""The requested delivery date: the date the customer asked to receive the goods or services - YYYY-MM-DD. Promised ship dates and payment due dates are not mapped here."""

    order_type: OptionalNullable[str] = UNSET
    r"""The order or transaction type of the sales order, as configured in the accounting system. On create, selects the type to create when the system supports several; omit to use the connection default. See the connector gotchas for the values each system accepts."""

    terms: OptionalNullable[str] = UNSET
    r"""Payment terms of the sales order."""

    terms_id: OptionalNullable[str] = UNSET
    r"""The ID of the payment terms"""

    po_number: OptionalNullable[str] = UNSET
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""

    reference: OptionalNullable[str] = UNSET
    r"""Optional reference identifier for the transaction."""

    status: Annotated[
        OptionalNullable[SalesOrderStatus], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Sales order status, in order of precedence: `cancelled`; `closed` (the order is closed or completed, whether or not it was billed); `invoiced` (fully billed but not yet closed); `back_ordered`; `on_hold` (including credit hold); `draft` (including pending approval); `open` (every other active state, including partially shipped and partially invoiced); `other` for states that fit none of these."""

    currency: Annotated[
        OptionalNullable[Currency], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""

    currency_rate: OptionalNullable[float] = UNSET
    r"""Currency Exchange Rate at the time entity was recorded/generated."""

    tax_inclusive: OptionalNullable[bool] = UNSET
    r"""Amounts are including tax"""

    sub_total: OptionalNullable[float] = UNSET
    r"""Sub-total amount, normally before tax."""

    total_tax: OptionalNullable[float] = UNSET
    r"""Total tax amount applied to this sales order."""

    tax_code: OptionalNullable[str] = UNSET
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""

    discount_percentage: OptionalNullable[float] = UNSET
    r"""Discount percentage applied to this sales order."""

    discount_amount: OptionalNullable[float] = UNSET
    r"""Discount amount applied to this sales order."""

    total: OptionalNullable[float] = UNSET
    r"""Total amount of the sales order, including tax."""

    unbilled_amount: OptionalNullable[float] = UNSET
    r"""Amount of the sales order not yet invoiced. Not the amount owed: see `balance` on the invoices created from the order for that."""

    shipping_method: OptionalNullable[str] = UNSET
    r"""Shipping method or carrier code for the order."""

    payment_method: OptionalNullable[str] = UNSET
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""

    customer_memo: OptionalNullable[str] = UNSET
    r"""Message to the customer, shown on the sales order."""

    notes: OptionalNullable[str] = UNSET
    r"""Internal notes for the sales order, not shown to the customer."""

    line_items: Optional[List[InvoiceLineItem]] = None

    billing_address: Optional[Address] = None

    shipping_address: Optional[Address] = None

    tracking_categories: OptionalNullable[List[Nullable[LinkedTrackingCategory]]] = (
        UNSET
    )
    r"""A list of linked tracking categories."""

    template_id: OptionalNullable[str] = UNSET
    r"""Optional sales order template"""

    source_document_url: OptionalNullable[str] = UNSET
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app."""

    custom_mappings: OptionalNullable[Dict[str, Any]] = UNSET
    r"""When custom mappings are configured on the resource, the result is included here."""

    custom_fields: Optional[List[CustomField]] = None

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    updated_by: OptionalNullable[str] = UNSET
    r"""The user who last updated the object."""

    created_by: OptionalNullable[str] = UNSET
    r"""The user who created the object."""

    updated_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was last updated."""

    created_at: OptionalNullable[datetime] = UNSET
    r"""The date and time when the object was created."""

    pass_through: Optional[List[PassThroughBody]] = None
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.SalesOrderStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("currency")
    def serialize_currency(self, value):
        if isinstance(value, str):
            try:
                return models.Currency(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "id",
            "downstream_id",
            "number",
            "customer",
            "quote_id",
            "invoice_id",
            "company_id",
            "department_id",
            "location_id",
            "project_id",
            "subsidiary_id",
            "order_date",
            "delivery_date",
            "order_type",
            "terms",
            "terms_id",
            "po_number",
            "reference",
            "status",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "sub_total",
            "total_tax",
            "tax_code",
            "discount_percentage",
            "discount_amount",
            "total",
            "unbilled_amount",
            "shipping_method",
            "payment_method",
            "customer_memo",
            "notes",
            "line_items",
            "billing_address",
            "shipping_address",
            "tracking_categories",
            "template_id",
            "source_document_url",
            "custom_mappings",
            "custom_fields",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
            "pass_through",
        ]
        nullable_fields = [
            "downstream_id",
            "number",
            "customer",
            "quote_id",
            "invoice_id",
            "company_id",
            "department_id",
            "location_id",
            "subsidiary_id",
            "order_date",
            "delivery_date",
            "order_type",
            "terms",
            "terms_id",
            "po_number",
            "reference",
            "status",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "sub_total",
            "total_tax",
            "tax_code",
            "discount_percentage",
            "discount_amount",
            "total",
            "unbilled_amount",
            "shipping_method",
            "payment_method",
            "customer_memo",
            "notes",
            "tracking_categories",
            "template_id",
            "source_document_url",
            "custom_mappings",
            "row_version",
            "updated_by",
            "created_by",
            "updated_at",
            "created_at",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class SalesOrderInputTypedDict(TypedDict):
    number: NotRequired[Nullable[str]]
    r"""Sales order number, as assigned by the accounting system."""
    customer: NotRequired[Nullable[LinkedCustomerInputTypedDict]]
    r"""The customer this entity is linked to."""
    quote_id: NotRequired[Nullable[str]]
    r"""The unique identifier for the quote."""
    company_id: NotRequired[Nullable[str]]
    r"""The company ID the transaction belongs to"""
    department_id: NotRequired[Nullable[str]]
    r"""The ID of the department"""
    location_id: NotRequired[Nullable[str]]
    r"""The ID of the location"""
    project_id: NotRequired[str]
    r"""The unique identifier for the linked project."""
    subsidiary_id: NotRequired[Nullable[str]]
    r"""The ID of the subsidiary"""
    order_date: NotRequired[Nullable[date]]
    r"""Date the sales order was placed - YYYY-MM-DD."""
    delivery_date: NotRequired[Nullable[date]]
    r"""The requested delivery date: the date the customer asked to receive the goods or services - YYYY-MM-DD. Promised ship dates and payment due dates are not mapped here."""
    order_type: NotRequired[Nullable[str]]
    r"""The order or transaction type of the sales order, as configured in the accounting system. On create, selects the type to create when the system supports several; omit to use the connection default. See the connector gotchas for the values each system accepts."""
    terms: NotRequired[Nullable[str]]
    r"""Payment terms of the sales order."""
    terms_id: NotRequired[Nullable[str]]
    r"""The ID of the payment terms"""
    po_number: NotRequired[Nullable[str]]
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""
    reference: NotRequired[Nullable[str]]
    r"""Optional reference identifier for the transaction."""
    status: NotRequired[Nullable[SalesOrderStatus]]
    r"""Sales order status, in order of precedence: `cancelled`; `closed` (the order is closed or completed, whether or not it was billed); `invoiced` (fully billed but not yet closed); `back_ordered`; `on_hold` (including credit hold); `draft` (including pending approval); `open` (every other active state, including partially shipped and partially invoiced); `other` for states that fit none of these."""
    currency: NotRequired[Nullable[Currency]]
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""
    currency_rate: NotRequired[Nullable[float]]
    r"""Currency Exchange Rate at the time entity was recorded/generated."""
    tax_inclusive: NotRequired[Nullable[bool]]
    r"""Amounts are including tax"""
    sub_total: NotRequired[Nullable[float]]
    r"""Sub-total amount, normally before tax."""
    total_tax: NotRequired[Nullable[float]]
    r"""Total tax amount applied to this sales order."""
    tax_code: NotRequired[Nullable[str]]
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""
    discount_percentage: NotRequired[Nullable[float]]
    r"""Discount percentage applied to this sales order."""
    discount_amount: NotRequired[Nullable[float]]
    r"""Discount amount applied to this sales order."""
    total: NotRequired[Nullable[float]]
    r"""Total amount of the sales order, including tax."""
    shipping_method: NotRequired[Nullable[str]]
    r"""Shipping method or carrier code for the order."""
    payment_method: NotRequired[Nullable[str]]
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""
    customer_memo: NotRequired[Nullable[str]]
    r"""Message to the customer, shown on the sales order."""
    notes: NotRequired[Nullable[str]]
    r"""Internal notes for the sales order, not shown to the customer."""
    line_items: NotRequired[List[InvoiceLineItemInputTypedDict]]
    billing_address: NotRequired[AddressTypedDict]
    shipping_address: NotRequired[AddressTypedDict]
    tracking_categories: NotRequired[
        Nullable[List[Nullable[LinkedTrackingCategoryTypedDict]]]
    ]
    r"""A list of linked tracking categories."""
    template_id: NotRequired[Nullable[str]]
    r"""Optional sales order template"""
    source_document_url: NotRequired[Nullable[str]]
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app."""
    custom_fields: NotRequired[List[CustomFieldTypedDict]]
    row_version: NotRequired[Nullable[str]]
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""
    pass_through: NotRequired[List[PassThroughBodyTypedDict]]
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""


class SalesOrderInput(BaseModel):
    number: OptionalNullable[str] = UNSET
    r"""Sales order number, as assigned by the accounting system."""

    customer: OptionalNullable[LinkedCustomerInput] = UNSET
    r"""The customer this entity is linked to."""

    quote_id: OptionalNullable[str] = UNSET
    r"""The unique identifier for the quote."""

    company_id: OptionalNullable[str] = UNSET
    r"""The company ID the transaction belongs to"""

    department_id: OptionalNullable[str] = UNSET
    r"""The ID of the department"""

    location_id: OptionalNullable[str] = UNSET
    r"""The ID of the location"""

    project_id: Optional[str] = None
    r"""The unique identifier for the linked project."""

    subsidiary_id: OptionalNullable[str] = UNSET
    r"""The ID of the subsidiary"""

    order_date: OptionalNullable[date] = UNSET
    r"""Date the sales order was placed - YYYY-MM-DD."""

    delivery_date: OptionalNullable[date] = UNSET
    r"""The requested delivery date: the date the customer asked to receive the goods or services - YYYY-MM-DD. Promised ship dates and payment due dates are not mapped here."""

    order_type: OptionalNullable[str] = UNSET
    r"""The order or transaction type of the sales order, as configured in the accounting system. On create, selects the type to create when the system supports several; omit to use the connection default. See the connector gotchas for the values each system accepts."""

    terms: OptionalNullable[str] = UNSET
    r"""Payment terms of the sales order."""

    terms_id: OptionalNullable[str] = UNSET
    r"""The ID of the payment terms"""

    po_number: OptionalNullable[str] = UNSET
    r"""A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order."""

    reference: OptionalNullable[str] = UNSET
    r"""Optional reference identifier for the transaction."""

    status: Annotated[
        OptionalNullable[SalesOrderStatus], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Sales order status, in order of precedence: `cancelled`; `closed` (the order is closed or completed, whether or not it was billed); `invoiced` (fully billed but not yet closed); `back_ordered`; `on_hold` (including credit hold); `draft` (including pending approval); `open` (every other active state, including partially shipped and partially invoiced); `other` for states that fit none of these."""

    currency: Annotated[
        OptionalNullable[Currency], PlainValidator(validate_open_enum(False))
    ] = UNSET
    r"""Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."""

    currency_rate: OptionalNullable[float] = UNSET
    r"""Currency Exchange Rate at the time entity was recorded/generated."""

    tax_inclusive: OptionalNullable[bool] = UNSET
    r"""Amounts are including tax"""

    sub_total: OptionalNullable[float] = UNSET
    r"""Sub-total amount, normally before tax."""

    total_tax: OptionalNullable[float] = UNSET
    r"""Total tax amount applied to this sales order."""

    tax_code: OptionalNullable[str] = UNSET
    r"""Applicable tax id/code override if tax is not supplied on a line item basis."""

    discount_percentage: OptionalNullable[float] = UNSET
    r"""Discount percentage applied to this sales order."""

    discount_amount: OptionalNullable[float] = UNSET
    r"""Discount amount applied to this sales order."""

    total: OptionalNullable[float] = UNSET
    r"""Total amount of the sales order, including tax."""

    shipping_method: OptionalNullable[str] = UNSET
    r"""Shipping method or carrier code for the order."""

    payment_method: OptionalNullable[str] = UNSET
    r"""Payment method used for the transaction, such as cash, credit card, bank transfer, or check"""

    customer_memo: OptionalNullable[str] = UNSET
    r"""Message to the customer, shown on the sales order."""

    notes: OptionalNullable[str] = UNSET
    r"""Internal notes for the sales order, not shown to the customer."""

    line_items: Optional[List[InvoiceLineItemInput]] = None

    billing_address: Optional[Address] = None

    shipping_address: Optional[Address] = None

    tracking_categories: OptionalNullable[List[Nullable[LinkedTrackingCategory]]] = (
        UNSET
    )
    r"""A list of linked tracking categories."""

    template_id: OptionalNullable[str] = UNSET
    r"""Optional sales order template"""

    source_document_url: OptionalNullable[str] = UNSET
    r"""URL link to a source document - shown as 'Go to [appName]' in the downstream app."""

    custom_fields: Optional[List[CustomField]] = None

    row_version: OptionalNullable[str] = UNSET
    r"""A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."""

    pass_through: Optional[List[PassThroughBody]] = None
    r"""The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."""

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.SalesOrderStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("currency")
    def serialize_currency(self, value):
        if isinstance(value, str):
            try:
                return models.Currency(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "number",
            "customer",
            "quote_id",
            "company_id",
            "department_id",
            "location_id",
            "project_id",
            "subsidiary_id",
            "order_date",
            "delivery_date",
            "order_type",
            "terms",
            "terms_id",
            "po_number",
            "reference",
            "status",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "sub_total",
            "total_tax",
            "tax_code",
            "discount_percentage",
            "discount_amount",
            "total",
            "shipping_method",
            "payment_method",
            "customer_memo",
            "notes",
            "line_items",
            "billing_address",
            "shipping_address",
            "tracking_categories",
            "template_id",
            "source_document_url",
            "custom_fields",
            "row_version",
            "pass_through",
        ]
        nullable_fields = [
            "number",
            "customer",
            "quote_id",
            "company_id",
            "department_id",
            "location_id",
            "subsidiary_id",
            "order_date",
            "delivery_date",
            "order_type",
            "terms",
            "terms_id",
            "po_number",
            "reference",
            "status",
            "currency",
            "currency_rate",
            "tax_inclusive",
            "sub_total",
            "total_tax",
            "tax_code",
            "discount_percentage",
            "discount_amount",
            "total",
            "shipping_method",
            "payment_method",
            "customer_memo",
            "notes",
            "tracking_categories",
            "template_id",
            "source_document_url",
            "row_version",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
