"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify import models, utils
from apideck_unify.types import BaseModel
from apideck_unify.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import ConfigDict, field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Mode(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Mode of the webhook support."""

    NATIVE = "native"
    VIRTUAL = "virtual"
    NONE = "none"


class SubscriptionLevel(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Received events are scoped to connection or across integration."""

    CONNECTION = "connection"
    INTEGRATION = "integration"


class ManagedVia(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""How the subscription is managed in the downstream."""

    MANUAL = "manual"
    API = "api"


class Unit(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The window unit for the rate."""

    SECOND = "second"
    MINUTE = "minute"
    HOUR = "hour"
    DAY = "day"


class RequestRateTypedDict(TypedDict):
    r"""The rate at which requests for resources will be made to downstream."""

    rate: int
    r"""The number of requests per window unit."""
    size: int
    r"""Size of request window."""
    unit: Unit
    r"""The window unit for the rate."""


class RequestRate(BaseModel):
    r"""The rate at which requests for resources will be made to downstream."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    rate: int
    r"""The number of requests per window unit."""

    size: int
    r"""Size of request window."""

    unit: Annotated[Unit, PlainValidator(validate_open_enum(False))]
    r"""The window unit for the rate."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @field_serializer("unit")
    def serialize_unit(self, value):
        if isinstance(value, str):
            try:
                return models.Unit(value)
            except ValueError:
                return value
        return value


class WebhookSupportResourcesTypedDict(TypedDict):
    events: NotRequired[List[str]]


class WebhookSupportResources(BaseModel):
    events: Optional[List[str]] = None


class VirtualWebhooksTypedDict(TypedDict):
    r"""Virtual webhook config for the connector."""

    request_rate: RequestRateTypedDict
    r"""The rate at which requests for resources will be made to downstream."""
    resources: NotRequired[Dict[str, WebhookSupportResourcesTypedDict]]
    r"""The resources that will be requested from downstream."""


class VirtualWebhooks(BaseModel):
    r"""Virtual webhook config for the connector."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    request_rate: RequestRate
    r"""The rate at which requests for resources will be made to downstream."""

    resources: Optional[Dict[str, WebhookSupportResources]] = None
    r"""The resources that will be requested from downstream."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class WebhookSupportTypedDict(TypedDict):
    r"""How webhooks are supported for the connector. Sometimes the connector natively supports webhooks, other times Apideck virtualizes them based on polling."""

    mode: NotRequired[Mode]
    r"""Mode of the webhook support."""
    subscription_level: NotRequired[SubscriptionLevel]
    r"""Received events are scoped to connection or across integration."""
    managed_via: NotRequired[ManagedVia]
    r"""How the subscription is managed in the downstream."""
    virtual_webhooks: NotRequired[VirtualWebhooksTypedDict]
    r"""Virtual webhook config for the connector."""


class WebhookSupport(BaseModel):
    r"""How webhooks are supported for the connector. Sometimes the connector natively supports webhooks, other times Apideck virtualizes them based on polling."""

    mode: Annotated[Optional[Mode], PlainValidator(validate_open_enum(False))] = None
    r"""Mode of the webhook support."""

    subscription_level: Annotated[
        Optional[SubscriptionLevel], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Received events are scoped to connection or across integration."""

    managed_via: Annotated[
        Optional[ManagedVia], PlainValidator(validate_open_enum(False))
    ] = None
    r"""How the subscription is managed in the downstream."""

    virtual_webhooks: Optional[VirtualWebhooks] = None
    r"""Virtual webhook config for the connector."""

    @field_serializer("mode")
    def serialize_mode(self, value):
        if isinstance(value, str):
            try:
                return models.Mode(value)
            except ValueError:
                return value
        return value

    @field_serializer("subscription_level")
    def serialize_subscription_level(self, value):
        if isinstance(value, str):
            try:
                return models.SubscriptionLevel(value)
            except ValueError:
                return value
        return value

    @field_serializer("managed_via")
    def serialize_managed_via(self, value):
        if isinstance(value, str):
            try:
                return models.ManagedVia(value)
            except ValueError:
                return value
        return value
