"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from apideck_unify.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from apideck_unify.utils import FieldMetadata
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhookEventLogsFilterServiceTypedDict(TypedDict):
    id: NotRequired[str]


class WebhookEventLogsFilterService(BaseModel):
    id: Annotated[Optional[str], FieldMetadata(query=True)] = None


class WebhookEventLogsFilterTypedDict(TypedDict):
    exclude_apis: NotRequired[Nullable[str]]
    service: NotRequired[Nullable[WebhookEventLogsFilterServiceTypedDict]]
    consumer_id: NotRequired[Nullable[str]]
    entity_type: NotRequired[Nullable[str]]
    event_type: NotRequired[Nullable[str]]
    start_date: NotRequired[Nullable[datetime]]
    r"""Filter logs at or after this ISO 8601 date-time (inclusive)."""
    end_date: NotRequired[Nullable[datetime]]
    r"""Filter logs at or before this ISO 8601 date-time (inclusive). Must be on or after start_date."""
    success: NotRequired[Nullable[bool]]
    r"""Filter by delivery success or failure."""
    status_code: NotRequired[Nullable[float]]
    r"""Filter by a single HTTP status code. For backward compatibility - use status_codes for multiple values."""
    status_codes: NotRequired[Nullable[List[float]]]
    r"""Filter by multiple HTTP status codes. Values must be between 100-599. Maximum 50 status codes allowed."""
    event_id: NotRequired[Nullable[str]]
    r"""Filter by webhook event ID."""
    execution_attempt: NotRequired[Nullable[float]]
    r"""Filter by the delivery attempt number."""


class WebhookEventLogsFilter(BaseModel):
    exclude_apis: Annotated[OptionalNullable[str], FieldMetadata(query=True)] = UNSET

    service: Annotated[
        OptionalNullable[WebhookEventLogsFilterService], FieldMetadata(query=True)
    ] = UNSET

    consumer_id: Annotated[OptionalNullable[str], FieldMetadata(query=True)] = UNSET

    entity_type: Annotated[OptionalNullable[str], FieldMetadata(query=True)] = UNSET

    event_type: Annotated[OptionalNullable[str], FieldMetadata(query=True)] = UNSET

    start_date: Annotated[OptionalNullable[datetime], FieldMetadata(query=True)] = UNSET
    r"""Filter logs at or after this ISO 8601 date-time (inclusive)."""

    end_date: Annotated[OptionalNullable[datetime], FieldMetadata(query=True)] = UNSET
    r"""Filter logs at or before this ISO 8601 date-time (inclusive). Must be on or after start_date."""

    success: Annotated[OptionalNullable[bool], FieldMetadata(query=True)] = UNSET
    r"""Filter by delivery success or failure."""

    status_code: Annotated[OptionalNullable[float], FieldMetadata(query=True)] = UNSET
    r"""Filter by a single HTTP status code. For backward compatibility - use status_codes for multiple values."""

    status_codes: Annotated[
        OptionalNullable[List[float]], FieldMetadata(query=True)
    ] = UNSET
    r"""Filter by multiple HTTP status codes. Values must be between 100-599. Maximum 50 status codes allowed."""

    event_id: Annotated[OptionalNullable[str], FieldMetadata(query=True)] = UNSET
    r"""Filter by webhook event ID."""

    execution_attempt: Annotated[OptionalNullable[float], FieldMetadata(query=True)] = (
        UNSET
    )
    r"""Filter by the delivery attempt number."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "exclude_apis",
            "service",
            "consumer_id",
            "entity_type",
            "event_type",
            "start_date",
            "end_date",
            "success",
            "status_code",
            "status_codes",
            "event_id",
            "execution_attempt",
        ]
        nullable_fields = [
            "exclude_apis",
            "service",
            "consumer_id",
            "entity_type",
            "event_type",
            "start_date",
            "end_date",
            "success",
            "status_code",
            "status_codes",
            "event_id",
            "execution_attempt",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
