"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from apideck_sdk.activities import Activities
from apideck_sdk.companies import Companies
from apideck_sdk.contacts import Contacts
from apideck_sdk.leads import Leads
from apideck_sdk.notes import Notes
from apideck_sdk.opportunities import Opportunities
from apideck_sdk.pipelines import Pipelines
from apideck_sdk.users import Users


class Crm(BaseSDK):
    companies: Companies
    contacts: Contacts
    opportunities: Opportunities
    leads: Leads
    pipelines: Pipelines
    notes: Notes
    users: Users
    activities: Activities

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.companies = Companies(self.sdk_configuration)
        self.contacts = Contacts(self.sdk_configuration)
        self.opportunities = Opportunities(self.sdk_configuration)
        self.leads = Leads(self.sdk_configuration)
        self.pipelines = Pipelines(self.sdk_configuration)
        self.notes = Notes(self.sdk_configuration)
        self.users = Users(self.sdk_configuration)
        self.activities = Activities(self.sdk_configuration)
