"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, HttpClient
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
from apideck_sdk import models, utils
from apideck_sdk._hooks import SDKHooks
from apideck_sdk.accounting import Accounting
from apideck_sdk.ats import Ats
from apideck_sdk.connector_sdk import ConnectorSDK
from apideck_sdk.crm import Crm
from apideck_sdk.ecommerce import Ecommerce
from apideck_sdk.filestorage import FileStorage
from apideck_sdk.hris import Hris
from apideck_sdk.issuetracking import IssueTracking
from apideck_sdk.models import internal
from apideck_sdk.sms import Sms
from apideck_sdk.types import OptionalNullable, UNSET
from apideck_sdk.vault import Vault
from apideck_sdk.webhook_sdk import WebhookSDK
import httpx
from typing import Any, Callable, Dict, Optional, Union


class Apideck(BaseSDK):
    r"""Apideck: The Apideck OpenAPI Spec: SDK Optimized
    https://developers.apideck.com - Apideck Developer Docs
    """

    accounting: Accounting
    ats: Ats
    crm: Crm
    ecommerce: Ecommerce
    file_storage: FileStorage
    hris: Hris
    sms: Sms
    issue_tracking: IssueTracking
    connector: ConnectorSDK
    vault: Vault
    webhook: WebhookSDK

    def __init__(
        self,
        api_key: Optional[Union[Optional[str], Callable[[], Optional[str]]]] = None,
        customer_id: Optional[str] = None,
        app_id: Optional[str] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param api_key: The api_key required for authentication
        :param customer_id: Configures the customer_id parameter for all supported operations
        :param app_id: Configures the app_id parameter for all supported operations
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        if client is None:
            client = httpx.Client()

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        if async_client is None:
            async_client = httpx.AsyncClient()

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if callable(api_key):
            security = lambda: models.Security(api_key=api_key())  # pylint: disable=unnecessary-lambda-assignment
        else:
            security = models.Security(api_key=api_key)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        _globals = internal.Globals(
            customer_id=utils.get_global_from_env(
                customer_id, "APIDECK_CUSTOMER_ID", str
            ),
            app_id=utils.get_global_from_env(app_id, "APIDECK_APP_ID", str),
        )

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                async_client=async_client,
                globals=_globals,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
        )

        hooks = SDKHooks()

        current_server_url, *_ = self.sdk_configuration.get_server_details()
        server_url, self.sdk_configuration.client = hooks.sdk_init(
            current_server_url, self.sdk_configuration.client
        )
        if current_server_url != server_url:
            self.sdk_configuration.server_url = server_url

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self._init_sdks()

    def _init_sdks(self):
        self.accounting = Accounting(self.sdk_configuration)
        self.ats = Ats(self.sdk_configuration)
        self.crm = Crm(self.sdk_configuration)
        self.ecommerce = Ecommerce(self.sdk_configuration)
        self.file_storage = FileStorage(self.sdk_configuration)
        self.hris = Hris(self.sdk_configuration)
        self.sms = Sms(self.sdk_configuration)
        self.issue_tracking = IssueTracking(self.sdk_configuration)
        self.connector = ConnectorSDK(self.sdk_configuration)
        self.vault = Vault(self.sdk_configuration)
        self.webhook = WebhookSDK(self.sdk_configuration)

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.sdk_configuration.client is not None:
            self.sdk_configuration.client.close()

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.sdk_configuration.async_client is not None:
            await self.sdk_configuration.async_client.aclose()
